services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ironshield-api:latest
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - IRONSHIELD_PRIVATE_KEY
      - IRONSHIELD_PUBLIC_KEY